-- =============================================
-- data.sql - 시드 데이터 진입점
-- =============================================
-- 이 파일은 Spring Boot의 기본 data.sql 로딩을 위한 placeholder입니다.
-- 실제 시드 데이터는 DataSourceInitConfig를 통해 db/seed/ 디렉토리의
-- 파일들을 순서대로 로드합니다.
--
-- 시드 파일 구조:
--   db/seed/V001__truncate_tables.sql - 테이블 초기화
--   db/seed/V002__tenants.sql         - 테넌트
--   db/seed/V003__departments.sql     - 부서
--   db/seed/V004__users.sql           - 사용자 (명시적 ID)
--   db/seed/V005__user_roles.sql      - 사용자 역할 (멀티롤 지원)
--   db/seed/V006__categories.sql      - 카테고리
--   db/seed/V007__contents.sql        - 콘텐츠
--   db/seed/V008__courses.sql         - 코스 + 태그 + 아이템
--   db/seed/V009__snapshots.sql       - 스냅샷 + LO + 아이템
--   db/seed/V010__course_times.sql    - 차수
--   db/seed/V011__enrollments.sql     - 수강
--   db/seed/V011_5__item_progress.sql - 아이템별 학습 진도
--   db/seed/V012__instructor_assignments.sql - 강사 배정
--   db/seed/V013__user_course_roles.sql      - 코스별 역할
--   db/seed/V014__community.sql       - 커뮤니티
--   db/seed/V015__cart_wishlist.sql   - 장바구니/찜
--   db/seed/V016__reviews.sql         - 리뷰
--   db/seed/V017__roadmaps.sql        - 로드맵
--
-- 환경 설정:
--   local, dev 프로파일에서만 시드 데이터 로드
--   spring.sql.init.mode=always 설정 필요
-- =============================================

-- 이 파일은 의도적으로 비어 있습니다.
-- 모든 시드 데이터는 DataSourceInitConfig에서 로드됩니다.

-- Spring Boot의 data.sql 실행 오류 방지를 위한 더미 문장
SELECT 1;
